#!/bin/bash
set -e

echo "============================================"
echo "  GonoPBX Installer"
echo "============================================"
echo ""

# Check prerequisites
command -v docker >/dev/null 2>&1 || { echo "ERROR: docker is not installed."; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "ERROR: docker compose is not available."; exit 1; }

echo "[OK] Docker and Docker Compose found."
echo ""

# Detect external IP
echo "Detecting external IP address..."
DETECTED_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || curl -s --max-time 5 icanhazip.com 2>/dev/null || echo "")

if [ -n "$DETECTED_IP" ]; then
    echo "Detected external IP: $DETECTED_IP"
    read -rp "Use this IP? [Y/n]: " USE_DETECTED
    if [ "$USE_DETECTED" = "n" ] || [ "$USE_DETECTED" = "N" ]; then
        read -rp "Enter external IP: " EXTERNAL_IP
    else
        EXTERNAL_IP="$DETECTED_IP"
    fi
else
    echo "Could not detect external IP automatically."
    read -rp "Enter external IP: " EXTERNAL_IP
fi

echo ""

# Admin password
read -rp "Set admin password (leave empty to auto-generate): " ADMIN_PASSWORD
if [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=' | head -c 20)
    echo "Generated admin password: $ADMIN_PASSWORD"
fi

# Generate secure random passwords
JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=')
DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')
AMI_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')

echo ""
echo "Generating configuration..."

# Create .env file
cat > .env <<EOF
# GonoPBX Configuration - generated by install.sh
EXTERNAL_IP=${EXTERNAL_IP}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
JWT_SECRET=${JWT_SECRET}
DB_PASSWORD=${DB_PASSWORD}
AMI_PASSWORD=${AMI_PASSWORD}
EOF

echo "[OK] .env created"

# Write manager.conf from template with generated AMI password
sed "s/%%AMI_PASSWORD%%/${AMI_PASSWORD}/" asterisk/config/manager.conf.template > asterisk/config/manager.conf

echo "[OK] manager.conf updated"

# Start containers
echo ""
echo "Starting containers..."
docker compose up -d --build

echo ""
echo "============================================"
echo "  GonoPBX Installation Complete!"
echo "============================================"
echo ""
echo "  Web GUI:    http://${EXTERNAL_IP}:3000"
echo "  API:        http://${EXTERNAL_IP}:8000"
echo ""
echo "  Login:      admin / ${ADMIN_PASSWORD}"
echo ""
echo "  Credentials are saved in .env"
echo "============================================"
